site_name: SPDX Specification v2.3.1-dev
copyright: Copyright &copy; 2010 - 2026 Linux Foundation and its Contributors.
docs_dir: chapters
theme:
  name: readthedocs
  hljs_languages:
  - abnf
extra_css:
- css/style.css
plugins:
- search
- mike:
    alias_type: redirect
markdown_extensions:
- codehilite:
   guess_lang: false
use_directory_urls: true
nav:
- 'Copyright': index.md
- 'Introduction': introduction.md
- 'Clause 1: Scope': scope.md
- 'Clause 2: Normative references': normative-references.md
- 'Clause 3: Terms and definitions': terms-and-definitions.md
- 'Clause 4: Conformance': conformance.md
- 'Clause 5: Composition of an SPDX document': composition-of-an-SPDX-document.md
- 'Clause 6: Document creation information': document-creation-information.md
- 'Clause 7: Package information': package-information.md
- 'Clause 8: File information': file-information.md
- 'Clause 9: Snippet information': snippet-information.md
- 'Clause 10: Other licensing information detected': other-licensing-information-detected.md
- 'Clause 11: Relationship between SPDX elements information': relationships-between-SPDX-elements.md
- 'Clause 12: Annotation information': annotations.md
- 'Clause 13: Review information (deprecated)': review-information-deprecated.md
- 'Annex A: SPDX License List': SPDX-license-list.md
- 'Annex B: License matching guidelines and templates': license-matching-guidelines-and-templates.md
- 'Annex C: RDF object model and identifier syntax': RDF-object-model-and-identifier-syntax.md
- 'Annex D: SPDX license expressions': SPDX-license-expressions.md
- 'Annex E: Using SPDX short identifiers in source files': using-SPDX-short-identifiers-in-source-files.md
- 'Annex F: External repository identifiers': external-repository-identifiers.md
- 'Annex G: SPDX Lite': SPDX-Lite.md
- 'Annex H: SPDX file tags': file-tags.md
- 'Annex I: Differences from earlier SPDX versions': diffs-from-previous-editions.md
- 'Annex J: Creative Commons Attribution License 3.0 Unported': creative-commons-attribution-license-3.0-unported.md
- 'Annex K: How to use SPDX in different scenarios': how-to-use.md
- 'Annex L: Compliance with regulation frameworks': regulations-compliance.md
- 'Bibliography': bibliography.md
exclude_docs: |
  foreword.md  # Used for ISO-submitted version only
