# Publish pre-3.0 specs (spec versions that do not require spec-parser)
# This workflow can be triggered manually or by a repository dispatch event.
# It has two parameters:
# - ref: The branch or tag to publish
# - aliases: Space-delimited aliases

on:
  repository_dispatch:
    types:
      - publish_spec
  workflow_dispatch:
    inputs:
      ref:
        description: Branch or tag to publish (e.g. refs/heads/support/2.3).
        required: true
        default: refs/heads/support/2.3
      aliases:
        description: Space-delimited aliases to publish (e.g. v2-latest v2-draft).
        required: false
jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.12
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8  #v5.0.0
      with:
        ref: ${{ github.event.client_payload.ref || github.event.inputs.ref }}
        path: spdx-spec
        fetch-depth: 0  # Because we will be pushing the gh-pages branch
    - name: Install pre-requisites
      run: pip install -r spdx-spec/requirements.txt
    - name: Install mike
      run: pip install mike==2.1.3
    - name: Extract branch or tag name
      id: extract-branch-or-tag-name
      run: |
        echo "REF_NAME=v${REF##*/}" >> $GITHUB_ENV
      env:
        REF: ${{ github.event.client_payload.ref || github.event.inputs.ref }}
    - name: Set Git identity
      working-directory: spdx-spec
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
    - name: Build docs
      working-directory: spdx-spec
      run: |
        mike deploy --update-aliases --push $REF_NAME ${{ github.event.inputs.aliases }}
