on: pull_request

jobs:
  validate:
    name: Validate build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout spdx-spec
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  #v7.0.1
      with:
        fetch-depth: 1
    - name: Set up specific Python version
      uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97  #v7.0.0
      with:
        python-version: "3.12"
        cache: "pip"
    - name: Install pre-requisites
      run: pip install -r requirements.txt
    - name: Build the site to validate (use mkdocs.yml, no model files, no PDF export)
      run: ENABLE_PDF_EXPORT=0 mkdocs build --clean --verbose
      # To validate the PR from within spdx-spec repo, build using mkdocs.yml
      # (no model files) and without the time-consuming PDF export
