on: pull_request

jobs:
  validate:
    name: Validate build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout spdx-spec
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  #v6.0.2
      with:
        fetch-depth: 1
    - name: Set up specific Python version
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  #v6.2.0
      with:
        python-version: "3.12"
        cache: "pip"
    - name: Install pre-requisites
      run: pip install -r requirements.txt
    - name: Build the site to validate (use mkdocs.yml, no model files, no PDF export)
      run: ENABLE_PDF_EXPORT=0 mkdocs build --clean --verbose
      # To validate the PR from within spdx-spec repo, build using mkdocs.yml
      # (no model files) and without the time-consuming PDF export
