on: pull_request

jobs:
  validate:
    name: Validate build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout spdx-spec
      uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955  #v4.3.0
      with:
        fetch-depth: 1
    - name: Set up specific Python version
      uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  #v5.6.0
      with:
        python-version: "3.12"
        cache: "pip"
    - name: Install pre-requisites
      run: pip install -r requirements.txt
    - name: Build the site to validate (use mkdocs.yml, no model files, no PDF export)
      run: ENABLE_PDF_EXPORT=0 mkdocs build --clean --verbose
      # To validate the PR from within spdx-spec repo, build using mkdocs.yml
      # (no model files) and without the time-consuming PDF export
