on:
  pull_request:
    paths:
      - 'examples/**/*.json'
      - 'docs/annexes/*.md'
  push:
    paths:
      - 'examples/**/*.json'
      - 'docs/annexes/*.md'

jobs:
  validate-examples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout spdx-spec
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  #v6.0.1
      - name: Set up specific Python version
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  #v6.2.0
        with:
          python-version: "3.12"
          cache: "pip"
      - name: Install Python dependencies
        run: |
          python3 -m pip install check-jsonschema==0.34.1 spdx3-validate==0.0.5
      - name: Install dependencies
        run: |
          sudo apt install -y gawk

      - name: Check examples
        run: |
          ./bin/check-examples.sh
