on:
  pull_request:
    paths:
      - 'examples/**/*.json'
      - 'docs/annexes/*.md'
  push:
    paths:
      - 'examples/**/*.json'
      - 'docs/annexes/*.md'

jobs:
  validate-examples:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout spdx-spec
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3  #v6.0.0
      - name: Set up specific Python version
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548  #v6.1.0
        with:
          python-version: "3.12"
          cache: "pip"
      - name: Install Python dependencies
        run: |
          python3 -m pip install check-jsonschema==0.34.1 spdx3-validate==0.0.5
      - name: Install dependencies
        run: |
          sudo apt install -y gawk

      - name: Check examples
        run: |
          ./bin/check-examples.sh
